### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by lchunleo** [michaelfig/mediasoup-broadcast-example#7]
when i run the PORT=8080 node server/index.js

i see the following issue, can advise how to resolve? i have already installed all the required packages:

/home/mediasoup-broadcast-example/node_modules/ws/lib/websocket.js:16
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/guest/mediasoup-broadcast-example/node_modules/ws/index.js:3:19)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by michaelfig** [comment]
What version of node are using?

**Comment by lchunleo** [comment]
> What version of node are using?

am running 4.2.6

**Comment by michaelfig** [comment]
That's ancient!  You'll need at least 8.x.

Good luck!

**Comment by lchunleo** [comment]
> That's ancient! You'll need at least 8.x.
> 
> Good luck!

Thank you for your advise. i updated my node and it is working perfect.

**Comment by michaelfig** [comment]
Great!  Glad it worked for you.
